# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - studentperformancendiaye

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3


    - name: Login to Azure Container Registry
      uses: docker/login-action@v3
      with:
        registry: testdockerniang.azurecr.io
        username: ${{ secrets.AzureAppService_ContainerUsername }}
        password: ${{ secrets.AzureAppService_ContainerPassword }}


    - name: Build and push image
      run: |

        docker build -t testdockerniang.azurecr.io/studentperformance:latest .

        docker push testdockerniang.azurecr.io/studentperformance:latest



  deploy:

    runs-on: ubuntu-latest

    needs: build

    steps:

    - name: Deploy to Azure Web App

      uses: azure/webapps-deploy@v2

      with:

        app-name: studentperformancendiaye

        publish-profile: ${{ secrets.AzureAppService_PublishProfile }}

        images: testdockerniang.azurecr.io/studentperformance:latest
